version: '3.9'

services:
  nodejs-service:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: nodejs-service 
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      mongo:
        condition: service_healthy
    # environment:
    #   - MONGODB_URI=mongodb://admin:admin@mongo:27017/products?directConnection=true&authSource=products

networks:
  my-network:
    name: my-network
